base_url = "https://BLinkseq.github.io/lastq/"
title = "Standard Linked-Read Format"
theme = "tanuki"
build_search_index = true
compile_sass = true

[extra]
mode = "docs"
github = "https://github.com/BLinkseq/lastq"
favicon = "/img/logo.png"
